### ISSUE TITLE
Making a selection in the no graze window (plant community) calendar does not populate the field

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#167]

**Comment by LisaMoore1** [comment]
@calebissharp in Chrome this still seems to be:
- not entering a value in the field after I make a calendar selection

**Comment by calebissharp** [comment]
@LisaMoore1 Is this the no grazing period for "timing" plant community actions? If so it should be fixed by #230.

**Comment by LisaMoore1** [comment]
OK. I’ll check with Micheal and make sure that everything has been moved to test. Thinking maybe this one hasn’t.

**Comment by calebissharp** [comment]
It looks like the PR hasn't been merged yet, so the changes it introduces won't show up in test. I can merge it though if you like.

**Comment by LisaMoore1** [comment]
K

**Comment by LisaMoore1** [comment]
@calebissharp I'm still not getting a date feeding into the no-graze windows (if I select timing in plant community actions). Might be something I'm doing but I tried completely logging out and shutting down/restarting chrome and safari on iPad and chrome on desktop and still not working. Suggestions?

**Comment by calebissharp** [comment]
@LisaMoore1 Not sure, maybe double check with @micheal-w-wells that the changes are actually deployed to test.

**Comment by LisaMoore1** [comment]
@micheal-w-wells can you take a look at this one? Not sure what’s up with it.

**Comment by LisaMoore1** [comment]
@micheal-w-wells actually all good.  Just checked again now.
